---
repos:
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.4.3-1
    hooks:
      - id: shfmt-docker
